spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?serverTimezone=UTC
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    encoding: UTF-8

  application:
    name: shop
  cloud:
    config:
      uri: http://localhost:8888